### ISSUE TITLE
ViteFonts is not a function

### ISSUE THREAD

**Issue by patrickjquinn** [stafyniaksacha/vite-plugin-fonts#18]
Whenever I import the plugin and use even the example given for Google's font set I get the following:

```failed to load config from /Users/pq/Developer/browser-ext/vite.config.ts
error during build:
TypeError: ViteFonts is not a function
    at file:///Users/pq/Developer/browser-ext/vite.config.ts.js?t=1651738748263:13:5
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadConfigFromFile (/Users/pq/Developer/browser-ext/node_modules/.pnpm/vite@2.9.8/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:61894:31)
    at async resolveConfig (/Users/pq/Developer/browser-ext/node_modules/.pnpm/vite@2.9.8/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:61436:28)
    at async doBuild (/Users/pq/Developer/browser-ext/node_modules/.pnpm/vite@2.9.8/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:41317:20)
    at async build (/Users/pq/Developer/browser-ext/node_modules/.pnpm/vite@2.9.8/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:41305:16)
    at async CAC.<anonymous> (/Users/pq/Developer/browser-ext/node_modules/.pnpm/vite@2.9.8/node_modules/vite/dist/node/cli.js:738:9)
 ELIFECYCLE  Command failed with exit code 1.```

**Comment by haunted-loaf** [comment]
I encountered the same issue.

I don't understand why the default export doesn't work, but using the named export worked for me:

```typescript
import { VitePluginFonts } from 'vite-plugin-fonts'

export default {
  plugins: [
    VitePluginFonts({
      google: {
        families: ['Source Sans Pro'],
      },
    }),
  ],
}
```

**Comment by tbusillo** [comment]
Experienced the same and as @haunted-loaf mentioned, using `VitePluginFonts` as a named import worked. Looks like `VitePluginFonts` is exported as the default and there is no export for `ViteFonts`. In other words, think the README just needs to be updated. 

For the maintainers: I don't mind updating the docs and submitting a PR, just let me know if you'd prefer me to hold off or want to address it another way.

**Comment by stafyniaksacha** [comment]
> From looking at the `index.ts`, `VitePluginFonts` is exported as the default and ViteFonts isn't exported at all (see below).

Hum, that's wired, the default export should work, maybe it's related to https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports

> Updating the examples to reflect the right import should address the issue and I don't mind doing it/submitting a PR. For the maintainers, if you would prefer I don't or want to handle it differently, just let me know!

I updated the readme to use the named export, which should work in any cases!
